Data and Inference Assignment 2

Victor Akinwande
Andrew ID: vakinwan




Que. 1.

Using the World Bank Indicators, download data for “GDP per
capita PPP (current international $)” and “Malnutrition prevalence,
weight for age (% of children under 5).”
What kind of relationship do you expect? Make a scatter plot of
malnutrition against GDP per capita PPP (using all available years
and countries). What kind of relationship do you see? Make a graph
for developing regions (six types and use one color for each). Make
a graph for income levels (nine types and one color for each).
Carefully label all graphs and provide legends.

In [13]:
import csv
import numpy
import matplotlib.pyplot as plt

data = numpy.ndarray(shape=(2,215,25), dtype=float, order='C')
data.fill(0)

def conv(s):
    try:
        if not s:
            s = 0.0
        s=float(s)
    except ValueError:
        pass    
    return s

with open('MALPre.csv') as csvfile:
    reader = csv.DictReader(csvfile)
    
    j  = 0
    
    for row in reader:
            
        
        data[0][j][0] = conv(row['1991'])
        data[0][j][1] = conv(row['1992'])
        data[0][j][2] = conv(row['1993'])
        data[0][j][3] = conv(row['1994'])
        data[0][j][4] = conv(row['1995'])
        data[0][j][5] = conv(row['1996'])
        data[0][j][6] = conv(row['1997'])
        data[0][j][7] = conv(row['1998'])
        data[0][j][8] = conv(row['1999'])
        data[0][j][9] = conv(row['2000'])
        data[0][j][10] = conv(row['2001'])
        data[0][j][11] = conv(row['2002'])
        data[0][j][12] = conv(row['2003'])
        data[0][j][13] = conv(row['2004'])
        data[0][j][14] = conv(row['2005'])
        data[0][j][15] = conv(row['2006'])
        data[0][j][16] = conv(row['2007'])
        data[0][j][17] = conv(row['2008'])
        data[0][j][18] = conv(row['2009'])
        data[0][j][19] = conv(row['2010'])
        data[0][j][20] = conv(row['2011'])
        data[0][j][21] = conv(row['2012'])
        data[0][j][22] = conv(row['2013'])
        data[0][j][23] = conv(row['2014'])
        data[0][j][24] = conv(row['2015'])
    
        
        j += 1
    
with open('GDPpc.csv') as csvfile:
    reader = csv.DictReader(csvfile)
    
    j  = 0
    
    for row in reader:
            
        
        data[1][j][0] = conv(row['1991'])
        data[1][j][1] = conv(row['1992'])
        data[1][j][2] = conv(row['1993'])
        data[1][j][3] = conv(row['1994'])
        data[1][j][4] = conv(row['1995'])
        data[1][j][5] = conv(row['1996'])
        data[1][j][6] = conv(row['1997'])
        data[1][j][7] = conv(row['1998'])
        data[1][j][8] = conv(row['1999'])
        data[1][j][9] = conv(row['2000'])
        data[1][j][10] = conv(row['2001'])
        data[1][j][11] = conv(row['2002'])
        data[1][j][12] = conv(row['2003'])
        data[1][j][13] = conv(row['2004'])
        data[1][j][14] = conv(row['2005'])
        data[1][j][15] = conv(row['2006'])
        data[1][j][16] = conv(row['2007'])
        data[1][j][17] = conv(row['2008'])
        data[1][j][18] = conv(row['2009'])
        data[1][j][19] = conv(row['2010'])
        data[1][j][20] = conv(row['2011'])
        data[1][j][21] = conv(row['2012'])
        data[1][j][22] = conv(row['2013'])
        data[1][j][23] = conv(row['2014'])
        data[1][j][24] = conv(row['2015'])
    
        
        j += 1
        
        
regions = ["" for x in range(215)]
countries = ["" for x in range(215)]


with open('Metadata.csv') as csvfile:
    
    reader = csv.DictReader(csvfile)
    i = 0
    for row in reader:
        regions[i] = row['Region']
        countries[i] = row['Country Code']
        i +=1
        
for x in range(0, 215):
    
    plt.plot(data[1][x], data[0][x], "o")   
        
        
plt.xlabel("GDP")
plt.ylabel("Malnutrition")
plt.text(60000, 50, "Each dot color represents a country", fontsize=12)
plt.show()    


for x in range(0, 215):
    
    if regions[x] == 'South Asia':
         sa, = plt.plot(data[1][x], data[0][x], "ro", label = "South Asia")  
    elif regions[x] == 'Middle East & North Africa':
         na, = plt.plot(data[1][x], data[0][x], "go", label = "MENA")    
    elif regions[x] == 'Latin America & Caribbean':
         la, = plt.plot(data[1][x], data[0][x], "bo", label = "LAC")  
    elif regions[x] == 'Sub-Saharan Africa':
         ssa, = plt.plot(data[1][x], data[0][x], "co", label = "SSA") 
    elif regions[x] == 'Europe & Central Asia':
         ec, = plt.plot(data[1][x], data[0][x], "ko", label = "ECA") 
    elif regions[x] == 'East Asia & Pacific':
         ea, = plt.plot(data[1][x], data[0][x], "yo", label = "EAP")

        
plt.xlabel("GDP")
plt.ylabel("Malnutrition")
plt.legend(handles = [sa, na, la, ssa, ec, ea])

plt.show()  



incomegrp = ["" for x in range(215)]

with open('Metadata.csv') as csvfile:
    
    reader = csv.DictReader(csvfile)
    i = 0
    for row in reader:
        incomegrp[i] = row['IncomeGroup']
        i +=1
li = 0        
for x in range(0, 215):
    
    if incomegrp[x] == 'Low income':
        li, = plt.plot(data[1][x], data[0][x], "ro", label="Low Income")  
    elif incomegrp[x] == 'Upper middle income':
        um, = plt.plot(data[1][x], data[0][x], "go", label= "Upper middle income")    
    elif incomegrp[x] == 'High income':
        hi, = plt.plot(data[1][x], data[0][x], "bo", label= "High income") 
    elif incomegrp[x] == 'Lower middle income':
        lm, = plt.plot(data[1][x], data[0][x], "yo", label="Lower middle income")  
        
plt.xlabel("GDP")
plt.ylabel("Malnutrition")

plt.legend(handles = [li, um, hi, lm])

plt.show()

![title](Q1grp1.png)
![title](Q1grp2.png)
![title](Q1grp3.png)

Thought Process:

After cleaning the data to allow for easy and correct processing,

I created a 3 dimensional numpy array, with dimensions 2 * 215 * 25. This way I could read each indicator (GDP and Malnutrition into the 2 rows of the first dimension rerspectively, I could read all the countries into the 215 row of the second dimension and I could read the 25 years into the third dimension.

With all the data inplace, all I needed to do in order to plot the indicators for the countries was loop through the array of the countries for each indicator and plot the corresponding values for each year.

To plot the regions, I looped through each row in the metadata file after reading the file, and then matched each country with the corresponding country in the my data array using its index. Since the metadata contained the region this allowed me to know which region the country belonged to, and plot with the corresponding grouping color for that region.

I did the same thing for the income level, only instead of the comparing with the title of the region in the matched index, I compared with the income levels.



Que. 2

Using Quandl, download data and synchronize the timestamps for
the time series pertinent to Maize Corn Price, Brent Crude Oil and
Gold in $. For each of the time series, compute the log returns and
on the same graph, plot the log returns against time. Label all the
axes appropriately and use a legend to distinguish the log returns for
each of the time series. From the results, which of the commodities
would make for a better investment over the long term?

In [ ]:
import quandl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

quandl.ApiConfig.api_key = 'yaNiCEXsWDEoxi3xxt_y'

Maize = quandl.get("ODA/PMAIZMT_USD", start_date="1980-01-31", end_date="2016-04-08")

Brent = quandl.get("ODA/POILBRE_USD", start_date="1980-01-31", end_date="2016-04-08")

Gold = quandl.get("BUNDESBANK/BBK01_WT5511", start_date="1980-01-31", end_date="2016-04-08")

Maize['lg_returns'] = np.log(Maize.Value) - np.log(Maize.Value.shift(1))
Brent['lg_returns'] = np.log(Brent.Value) - np.log(Brent.Value.shift(1))
Gold['lg_returns'] = np.log(Gold.Value) - np.log(Gold.Value.shift(1))


plt.plot(Maize['lg_returns'], label ='Maize')
plt.plot(Brent['lg_returns'], label ='Brent')
plt.plot(Gold['lg_returns'], label = 'Gold')

plt.xlabel("years")
plt.ylabel("log returns")
plt.legend()
plt.show()


![title](Q2grp1.png)

The quandl data was gotten using the quandl api, and python library. I synchronized the data by using a union join, and then computed the log return on every index in the each data frame except the first by computing the natural log of the value and subtracting from the natural log of the previous value.

Gold would make for a better investment over a long time because of its relative stability

Que. 3.

Download “Government expenditure on education, total (% of
government expenditure)” data from the World Bank Indicators.
Select the expenditure for all countries in 2010 and calculate summary
statistics. Provide a table giving the mean, median, standard
deviation, 5, 25, 75, and 95 percentiles.
Repeat the same process for “School enrolment, primary (% net).”

In [1]:
import pandas as pd 
from tabulate import tabulate
import numpy as np

primaryenrollment = pd.read_csv('primaryenrollment.csv')
expendonedu = pd.read_csv('expendonedu.csv')

primaryenrollment = primaryenrollment[pd.notnull(primaryenrollment['Country Name'])]
expenditurecol = expendonedu["2010"]
primaryenrollmentcol = primaryenrollment['2010 [YR2010]']

print(tabulate([['Govt. Expenditure', np.nanmean(expenditurecol), np.nanmedian(expenditurecol),
                 np.nanstd(expenditurecol)
                ,np.nanpercentile(expenditurecol, 5), np.nanpercentile(expenditurecol, 25), 
                 np.nanpercentile(expenditurecol, 75)
                ,np.nanpercentile(expenditurecol, 95)],
                ['Pr. Sch. Enrollment', np.nanmean(primaryenrollmentcol),np.nanmedian(primaryenrollmentcol)
                , np.nanstd(primaryenrollmentcol), np.nanpercentile(primaryenrollmentcol, 5),
                 np.nanpercentile(primaryenrollmentcol, 25)
                , np.nanpercentile(primaryenrollmentcol, 75), np.nanpercentile(primaryenrollmentcol, 95)]],
               
               headers=['Title', 'Mean', 'Median', 'Standard Dev',
                        '5th Percentile', '25th', '75th', '95th'], tablefmt='orgtbl'))


| Title               |    Mean |   Median |   Standard Dev |   5th Percentile |     25th |     75th |     95th |
|---------------------+---------+----------+----------------+------------------+----------+----------+----------|
| Govt. Expenditure   |  4.9676 |  4.63519 |         2.1251 |          2.40883 |  4.02503 |  5.53451 |  8.32526 |
| Pr. Sch. Enrollment | 90.4748 | 93.3782  |         8.9943 |         70.4809  | 87.8097  | 96.6307  | 99.3331  |


In [3]:
expendonedu

Country Name Country Code  \
0                                                Aruba          ABW   
1                                              Andorra          AND   
2                                          Afghanistan          AFG   
3                                               Angola          AGO   
4                                              Albania          ALB   
5                                           Arab World          ARB   
6                                 United Arab Emirates          ARE   
7                                            Argentina          ARG   
8                                              Armenia          ARM   
9                                       American Samoa          ASM   
10                                 Antigua and Barbuda          ATG   
11                                           Australia          AUS   
12                                             Austria          AUT   
13                                          Azerbaijan          AZE   
14                                             Burundi          BDI   
15                                             Belgium          BEL   
16                                               Benin          BEN   
17                                        Burkina Faso          BFA   
18                                          Bangladesh          BGD   
19                                            Bulgaria          BGR   
20                                             Bahrain          BHR   
21                                             Bahamas          The   
22                              Bosnia and Herzegovina          BIH   
23                                             Belarus          BLR   
24                                              Belize          BLZ   
25                                             Bermuda          BMU   
26                                             Bolivia          BOL   
27                                              Brazil          BRA   
28                                            Barbados          BRB   
29                                   Brunei Darussalam          BRN   
..                                                 ...          ...   
234  Middle East & North Africa (IDA & IBRD countries)          TMN   
235                                        Timor-Leste          TLS   
236                                              Tonga          TON   
237                            South Asia (IDA & IBRD)          TSA   
238          Sub-Saharan Africa (IDA & IBRD countries)          TSS   
239                                Trinidad and Tobago          TTO   
240                                            Tunisia          TUN   
241                                             Turkey          TUR   
242                                             Tuvalu          TUV   
243                                           Tanzania          TZA   
244                                             Uganda          UGA   
245                                            Ukraine          UKR   
246                                Upper middle income          UMC   
247                                            Uruguay          URY   
248                                      United States          USA   
249                                         Uzbekistan          UZB   
250                     St. Vincent and the Grenadines          VCT   
251                                          Venezuela           RB   
252                             British Virgin Islands          VGB   
253                              Virgin Islands (U.S.)          VIR   
254                                            Vietnam          VNM   
255                                            Vanuatu          VUT   
256                                 West Bank and Gaza          PSE   
257                                              World          WLD   
258                                              Samoa          WS

This is done simply by reading the data and calling the appropriate functions on the data.

Que.4.

The World Bank Indicators provide variables called “Fertility rate,
total (births per woman)” and “GDP per capita (current US$)”.
Make a scatter plot of Fertility rate versus GDP per capita for all
countries in 2010. Produce cumulative distribution functions for the
fertility rate variable using data from 1990 and 2010 respectively.
Use vertical lines to indicate the mean and median. Use a legend to
explain which is the mean and which is the median. Have fertility
rates changed over this twenty-year period?

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

fertility  = pd.read_csv('fertility.csv')['2010']
gdpusd = pd.read_csv('gdpusd.csv')['2010']

gdpusd = gdpusd.apply(lambda x: (x - gdpusd.min())/(gdpusd.max() - gdpusd.min()))
gdpusd = gdpusd.clip(lower=0.01, upper=0.99)

plt.scatter(fertility, gdpusd, label='gdp per capita')

fertility1990  = pd.read_csv('fertility.csv')['1990']
#to calc cdf, you need to sort

fertility1990_sorted = fertility1990.sort_values()
fertility2010_sorted = fertility.sort_values()

fertility1990_sorted[len(fertility1990_sorted)] = fertility1990_sorted.iloc[-1]
fertility1990_cum_dis = np.linspace(0.,1.,len(fertility1990_sorted))
fertility1990_cdf = pd.Series(fertility1990_cum_dis, index=fertility1990_sorted)

plt.plot(fertility1990_cdf, label='1990 Fertility CDF')

meanfertility1990 = np.nanmean(fertility1990)

plt.axvline(x = meanfertility1990, color = 'r', label='1990 Fertility Mean')

medianfertility1990 = np.nanmedian(fertility1990)

plt.axvline(x = medianfertility1990, color = 'c', label='1990 Fertility Median')

fertility2010_sorted[len(fertility2010_sorted)] = fertility2010_sorted.iloc[-1]
fertility2010_cum_dis = np.linspace(0.,1.,len(fertility2010_sorted))
fertility2010_cdf = pd.Series(fertility2010_cum_dis, index=fertility2010_sorted)

plt.plot(fertility2010_cdf, label='2010 Fertility CDF')
meanfertility2010 = np.nanmean(fertility)

plt.axvline(x = meanfertility2010, color = 'm', label='2010 Fertility Mean')

medianfertility2010 = np.nanmedian(fertility)

plt.axvline(x = medianfertility2010, color = 'y', label='2010 Fertility Median')



plt.ylabel('GDP or Probability')
plt.xlabel('Fertility')
plt.legend()
plt.show()


AttributeError: 'Series' object has no attribute 'linspace'

![title](Q4grp1.png)

The cumulative distribution function (cdf)for this question shows the probability that the fertility takes a value less than or equal to a value x. After reading the data the cummulative distribution was simply gotten by sorting the data, getting evenly spaced normalized numbers over 0 - 1, and this was plotted against the sorted data. 

The fertiliy rate has indeed decreased over this 20 year period. With the mean fertility rate shrinking to
2.89 in 2010 from 3.96 in 1990. Also the median fertility has also decreased from 3.60 to 2.39 within those 20 years.


Que. 5.

Download the latest data for the “Happy Planet Index” from
http://www.happyplanetindex.org and “Corruption Perceptions Index” from http://www.transparency.org/cpi2014/in_detail . Both datasets are available as excel spread-sheets.
Find matching countries for both indices and make a carefully labelled scatter plot
to demonstrate the relationship using ranks in both cases. Are there
any countries that stand out as being unusual? 

In [3]:
import pandas as pd
import numpy as np
from numpy.random import rand
import matplotlib.pyplot as plt
import matplotlib.cm as cm


hpi = pd.read_csv('hpi.csv').dropna()
cpi = pd.read_csv('CPI.csv').dropna()

hpi_countries = hpi['Country']

index = 0

Ranks = pd.DataFrame({'Country': ["" for x in range(len(cpi))], 'CPI': [0 for x in range(len(cpi))],
                      'HPI': [0 for x in range(len(cpi))]})

for country_name in cpi.Country:
   
    hpiindexlist = (hpi_countries[hpi_countries == country_name]).index.tolist()
    hpiindex = -1
    
    if len(hpiindexlist) > 0:
    
        hpiindex = hpiindexlist[0]
        Ranks.CPI[index] = index +1
        Ranks.HPI[index] = hpiindex + 1
        Ranks.Country[index] = country_name
        
    index = index + 1

CPI = Ranks.CPI[Ranks.CPI != 0]
HPI = Ranks.HPI[Ranks.HPI != 0]
Country = Ranks.Country[Ranks.Country != ""]

color=iter(cm.rainbow(np.linspace(0,1,len(CPI))))

plt.xlabel('HPI')
plt.ylabel('CPI')


for hpp, cpp,ct, in zip(HPI, CPI, Country):
    plt.scatter(hpp, cpp, color=next(color))
    plt.annotate(
        ct,  xy = (hpp, cpp), xytext = (-20, 20), textcoords = 'offset points', ha = 'right', va = 'bottom',
        arrowprops = dict(arrowstyle = '->', connectionstyle = 'arc2,rad=0'))
    
    
plt.show()


/home/vakinwande/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/vakinwande/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:27: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/vakinwande/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:28: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


ValueError: Unknown style : arc2,rad=0

![title](Q5grp1.png)

In [6]:
print cm.rainbow(np.linspace(0,1,len(CPI)))

[[  5.00000000e-01   0.00000000e+00   1.00000000e+00   1.00000000e+00]
 [  4.92156863e-01   1.23196595e-02   9.99981027e-01   1.00000000e+00]
 [  4.76470588e-01   3.69514994e-02   9.99829250e-01   1.00000000e+00]
 [  4.60784314e-01   6.15609061e-02   9.99525720e-01   1.00000000e+00]
 [  4.45098039e-01   8.61329395e-02   9.99070481e-01   1.00000000e+00]
 [  4.29411765e-01   1.10652682e-01   9.98463604e-01   1.00000000e+00]
 [  4.13725490e-01   1.35105247e-01   9.97705180e-01   1.00000000e+00]
 [  3.98039216e-01   1.59475791e-01   9.96795325e-01   1.00000000e+00]
 [  3.82352941e-01   1.83749518e-01   9.95734176e-01   1.00000000e+00]
 [  3.66666667e-01   2.07911691e-01   9.94521895e-01   1.00000000e+00]
 [  3.50980392e-01   2.31947641e-01   9.93158666e-01   1.00000000e+00]
 [  3.35294118e-01   2.55842778e-01   9.91644696e-01   1.00000000e+00]
 [  3.19607843e-01   2.79582593e-01   9.89980213e-01   1.00000000e+00]
 [  3.03921569e-01   3.03152674e-01   9.88165472e-01   1.00000000e+00]
 [  2.



The countries that stand out as unusual include some developing countries like chad, burundi, guinea with high corruption index yet have a high happiness index. Some developed countries like luxemborg, and australia with their low corruption index and high happiness index also stand out.

Interestingly countries like Norway, the UK that are quite rich (particularly Norway) are not very happy. I guess money indeed doesn't buy happiness.